[package]
id = charge_ring_viz

[id]
version = 0.1.4
name = charge_ring_viz

[ui]
is_visible = 1
label = Charge Ring
show_in_nav = 0

[launcher]
author = Tony Vincent
description = Battery/charge status as a ring gauge with animated dock
version = 0.1.4

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
